!**********************************************************************C
!                                                                      C
!     *** SUBROUTINE ARRAY_ALLOCATION ***                                      C

!**********************************************************************C
      
      SUBROUTINE ARRAY_ALLO
	  
		Module common_var
		IMPLICIT NONE
	  
! VALID This is used for model valiadation
		ALLOCATE (GEP_V(MAX_GRIDS,MAX_YEARS,12), ET_V(MAX_GRIDS,MAX_YEARS,12)&
		,GPP_V(MAX_GRIDS,MAX_YEARS),NPP_V(MAX_GRIDS,MAX_YEARS)&
		,RUNOFF_V(MAX_GRIDS,MAX_YEARS),RUN_OFF(MAX_GRIDS,MAX_YEARS) )
      

! CELLINFO
		ALLOCATE (HUCNO(MAX_GRIDS) )
		ALLOCATE (LADUSE(MAX_GRIDS),LATUDE(MAX_GRIDS),LONGI(MAX_GRIDS),HUCELE(MAX_GRIDS) )

! VEGINFO
		ALLOCATE (VEG(MAX_GRIDS,MAX_YEARS) )


! OUTPUT1
		ALLOCATE (PET(MAX_GRIDS,MAX_YEARS,12),PAET(MAX_GRIDS,MAX_YEARS,12),AET(MAX_GRIDS,MAX_YEARS, 12),&
		RUNOFF(MAX_GRIDS,MAX_YEARS,12) ,BASEFLOW(MAX_GRIDS,MAX_YEARS,12), PRIBF(MAX_GRIDS,MAX_YEARS,12) , &
		SECBF(MAX_GRIDS,MAX_YEARS,12) , TRUNOFF(MAX_GRIDS,MAX_YEARS,12), &
		INTF(MAX_GRIDS,MAX_YEARS,12), RUN_HRU(MAX_GRIDS,MAX_YEARS,12),BASE_HRU(MAX_GRIDS,MAX_YEARS,12) )  


! Monthly RUNOFF
		ALLOCATE (RUNOFF_MON(MAX_GRIDS,12),BASEFLOW_MON(MAX_GRIDS,12) )
      
! CLIMATE
		ALLOCATE (RAIN(MAX_GRIDS,MAX_YEARS,12), TEMP(MAX_GRIDS,MAX_YEARS,12), AAPPT(MAX_GRIDS) )
      
! LAI    
		ALLOCATE (LAI(MAX_GRIDS,MAX_YEARS,12) )

! SNOWPACK
		ALLOCATE (NSPM(MAX_GRIDS,MAX_YEARS) )
		ALLOCATE (SP(MAX_GRIDS,MAX_YEARS,12) )

! SUMMARY1
		ALLOCATE (NUM_Year(MAX_GRIDS) )
		ALLOCATE (ANURAIN(MAX_GRIDS,MAX_YEARS),ANURUN(MAX_GRIDS,MAX_YEARS),ANUPET(MAX_GRIDS,MAX_YEARS),&
		ANUAET(MAX_GRIDS,MAX_YEARS),ANUPAET(MAX_GRIDS,MAX_YEARS),&
		RAINALL(MAX_GRIDS), AETALL(MAX_GRIDS), PETALL(MAX_GRIDS), RUNALL(MAX_GRIDS), RUNRATIO(MAX_GRIDS),&
		ETRATIO_GRD(MAX_GRIDS),TRATIO(MAX_GRIDS),RALL(MAX_GRIDS) )

! SOIL parameters input
		ALLOCATE (LZTWM(MAX_GRIDS), LZFPM(MAX_GRIDS), LZFSM(MAX_GRIDS), LZSK(MAX_GRIDS),LZPK(MAX_GRIDS), UZTWM(MAX_GRIDS), &
		UZFWM(MAX_GRIDS),UZK(MAX_GRIDS), ZPERC(MAX_GRIDS),REXP(MAX_GRIDS), PFREE(MAX_GRIDS))

! Soil Mositure (AV-average,EM-end of month)
		ALLOCATE (AVSMC(MAX_GRIDS,MAX_YEARS,12),AVUZTWC(MAX_GRIDS,MAX_YEARS,12), AVUZFWC(MAX_GRIDS,MAX_YEARS,12), &
		AVLZTWC(MAX_GRIDS,MAX_YEARS,12), AVLZFPC(MAX_GRIDS,MAX_YEARS,12),AVLZFSC(MAX_GRIDS,MAX_YEARS,12), &
		EMSMC(MAX_GRIDS,MAX_YEARS,12),EMUZTWC(MAX_GRIDS,MAX_YEARS,12),EMUZFWC(MAX_GRIDS,MAX_YEARS,12),&
		EMLZTWC(MAX_GRIDS,MAX_YEARS,12), EMLZFPC(MAX_GRIDS,MAX_YEARS,12),EMLZFSC(MAX_GRIDS,MAX_YEARS,12) )
	   
! FLOW      
		ALLOCATE (STRFLOW(MAX_GRIDS,MAX_YEARS,12),STRET(MAX_GRIDS,MAX_YEARS,12),&
		STRGEP(MAX_GRIDS,MAX_YEARS,12) )

! CARBON
		ALLOCATE (NUM_YEAR_C(MAX_GRIDS) )
		ALLOCATE (GEPM(MAX_GRIDS,MAX_YEARS,12),RECOM(MAX_GRIDS,MAX_YEARS,12), &
		NEEM(MAX_GRIDS,MAX_YEARS,12),GEPA(MAX_GRIDS,MAX_YEARS),NEEA(MAX_GRIDS,MAX_YEARS),&
		AHUCGEP(MAX_GRIDS), AHUCNEE(MAX_GRIDS),AHUCRE(MAX_GRIDS) )
      
! HUCPETAET
		ALLOCATE (HUCAET(MAX_GRIDS,MAX_YEARS), HUCPET(MAX_GRIDS,MAX_YEARS),&
		HUCPAET(MAX_GRIDS,MAX_YEARS) )
  
! R	  
		ALLOCATE (RFACTOR(MAX_GRIDS,MAX_YEARS),ETRATIO(MAX_GRIDS,MAX_YEARS),&
		ARUNRT(MAX_GRIDS,MAX_YEARS), AETRT(MAX_GRIDS,MAX_YEARS) )
!RUNLAND 
		ALLOCATE (RUNLAND(NGRID,NYEAR,12,31),ETLAND(NGRID,NYEAR,12,31),GEPLAND(NGRID,NYEAR,12,31))

	RETURN
	
	END  