!**********************************************************************C
!                                                                      C
!     *** SUBROUTINE ARRAY_ALLOCATION ***                                      C

!**********************************************************************C
      
      SUBROUTINE ARRAY_ALLO
	  
		USE common_var
		IMPLICIT NONE
	ALLOCATE(BASEFLOW_V(NYEAR,12), FLOW_V(NYEAR,12),FLOW(NYEAR,12))
		 
  
! VALID This is used for model valiadation
		ALLOCATE (GEP_V(NGRID,NYEAR,12), ET_V(NGRID,NYEAR,12)&
		,GPP_V(NGRID,NYEAR),NPP_V(NGRID,NYEAR)&
		,RUNOFF_V(NGRID,NYEAR),RUN_OFF(NGRID,NYEAR) )
      

! CELLINFO
		ALLOCATE (HUCNO(NGRID) )
		ALLOCATE (LADUSE(NGRID),LATUDE(NGRID),LONGI(NGRID),HUCELE(NGRID) )

! VEGINFO
		ALLOCATE (VEG(NGRID,NYEAR) )


! OUTPUT1
		ALLOCATE (PET(NGRID,NYEAR,12),PAET(NGRID,NYEAR,12),AET(NGRID,NYEAR, 12),&
		RUNOFF(NGRID,NYEAR,12) ,BASEFLOW(NGRID,NYEAR,12), PRIBF(NGRID,NYEAR,12) , &
		SECBF(NGRID,NYEAR,12) , TRUNOFF(NGRID,NYEAR,12), &
		INTF(NGRID,NYEAR,12), RUN_HRU(NGRID,NYEAR,12),BASE_HRU(NGRID,NYEAR,12) )  


! Monthly RUNOFF
		ALLOCATE (RUNOFF_MON(NGRID,12),BASEFLOW_MON(NGRID,12) )
      
! CLIMATE
		ALLOCATE (RAIN(NGRID,NYEAR,12), TEMP(NGRID,NYEAR,12), AAPPT(NGRID) )
      
! LAI    
		ALLOCATE (LAI(NGRID,NYEAR,12) )

! SNOWPACK
		ALLOCATE (NSPM(NGRID,NYEAR) )
		ALLOCATE (SP(NGRID,NYEAR,12) )

! SUMMARY1
		ALLOCATE (NUM_Year(NGRID) )
		ALLOCATE (ANURAIN(NGRID,NYEAR),ANURUN(NGRID,NYEAR),ANUPET(NGRID,NYEAR),&
		ANUAET(NGRID,NYEAR),ANUPAET(NGRID,NYEAR),&
		RAINALL(NGRID), AETALL(NGRID), PETALL(NGRID), RUNALL(NGRID), RUNRATIO(NGRID),&
		ETRATIO_GRD(NGRID),TRATIO(NGRID),RALL(NGRID) )

! SOIL parameters input
		ALLOCATE (LZTWM(NGRID), LZFPM(NGRID), LZFSM(NGRID), LZSK(NGRID),LZPK(NGRID), UZTWM(NGRID), &
		UZFWM(NGRID),UZK(NGRID), ZPERC(NGRID),REXP(NGRID), PFREE(NGRID))

! Soil Mositure (AV-average,EM-end of month)
		ALLOCATE (AVSMC(NGRID,NYEAR,12),AVUZTWC(NGRID,NYEAR,12), AVUZFWC(NGRID,NYEAR,12), &
		AVLZTWC(NGRID,NYEAR,12), AVLZFPC(NGRID,NYEAR,12),AVLZFSC(NGRID,NYEAR,12), &
		EMSMC(NGRID,NYEAR,12),EMUZTWC(NGRID,NYEAR,12),EMUZFWC(NGRID,NYEAR,12),&
		EMLZTWC(NGRID,NYEAR,12), EMLZFPC(NGRID,NYEAR,12),EMLZFSC(NGRID,NYEAR,12) )
	   
! FLOW      
		ALLOCATE (STRFLOW(NGRID,NYEAR,12),STRET(NGRID,NYEAR,12),&
		STRGEP(NGRID,NYEAR,12) )

! CARBON
		ALLOCATE (NUM_YEAR_C(NGRID) )
		ALLOCATE (GEPM(NGRID,NYEAR,12),RECOM(NGRID,NYEAR,12), &
		NEEM(NGRID,NYEAR,12),GEPA(NGRID,NYEAR),REOA(NGRID,NYEAR),NEEA(NGRID,NYEAR),&
		AHUCGEP(NGRID), AHUCNEE(NGRID),AHUCRE(NGRID) )
      
! HUCPETAET
		ALLOCATE (HUCAET(NGRID,NYEAR), HUCPET(NGRID,NYEAR),&
		HUCPAET(NGRID,NYEAR) )
  
! R	  
		ALLOCATE (RFACTOR(NGRID,NYEAR),ETRATIO(NGRID,NYEAR),&
		ARUNRT(NGRID,NYEAR), AETRT(NGRID,NYEAR) )
!RUNLAND 
		ALLOCATE (RUNLAND(NGRID,NYEAR,12,31),ETLAND(NGRID,NYEAR,12,31),GEPLAND(NGRID,NYEAR,12,31))

	RETURN
	
	END  
