!******************Defining Common Variables for the whole program********

      Module common_var
      implicit none

! Grid numbers
      INTEGER MAX_GRIDS, MAX_YEARS,MAX_HUCS
      PARAMETER (MAX_GRIDS=10108,MAX_YEARS=32,MAX_HUCS=20)	 
! WUE
	 REAL wue_k,reco_inter,reco_slope 
	 COMMON/WUE/wue_k(MAX_HUCS),reco_inter(MAX_HUCS),reco_slope(MAX_HUCS)
	 
! BASIC
      INTEGER NGRID,NYEAR,NLC,BYEAR,IYSTART,IYEND,LAI_S_Y,LAI_E_Y,modelscale  
      COMMON/BASIC/NGRID,NYEAR,NLC,BYEAR,IYSTART,IYEND,LAI_S_Y,LAI_E_Y,modelscale
		!! Scale is grid or catchment scale

! VALID This is used for model valiadation
      REAL GEP_V,ET_V,GPP_V,NPP_V,FLOW_V,FLOW,RUNOFF_V,RUN_OFF,BASEFLOW_V
        
      COMMON/VALID/ GEP_V(MAX_GRIDS,MAX_YEARS,12), ET_V(MAX_GRIDS,MAX_YEARS,12)&
          ,GPP_V(MAX_GRIDS,MAX_YEARS),NPP_V(MAX_GRIDS,MAX_YEARS), FLOW_V(MAX_YEARS,12),FLOW(MAX_YEARS,12)&
          ,RUNOFF_V(MAX_GRIDS,MAX_YEARS),RUN_OFF(MAX_GRIDS,MAX_YEARS), &
          BASEFLOW_V(MAX_YEARS,12)

! CELLINFO
      REAL LATUDE,LONGI,HUCELE
      INTEGER HUCNO,LADUSE,LADUSE_lc
      COMMON/CELLINFO/LADUSE(MAX_GRIDS),LADUSE_lc(MAX_GRIDS,MAX_HUCS),&
			HUCNO(MAX_GRIDS),LATUDE(MAX_GRIDS),LONGI(MAX_GRIDS),HUCELE(MAX_GRIDS)

! VEGINFO
      INTEGER veg
      COMMON/VEGINFO/VEG(MAX_GRIDS,MAX_YEARS)


! OUTPUT1
      REAL PET,PAET,AET,RUNOFF,BASEFLOW,PRIBF,SECBF,INTF,TRUNOFF, &
         RUN_HRU,BASE_HRU
      COMMON/OUTPUT1/ PET(MAX_GRIDS,MAX_YEARS,12),PAET(MAX_GRIDS,MAX_YEARS,12),AET(MAX_GRIDS,MAX_YEARS, 12),&
          RUNOFF(MAX_GRIDS,MAX_YEARS,12) ,BASEFLOW(MAX_GRIDS,MAX_YEARS,12), PRIBF(MAX_GRIDS,MAX_YEARS,12) , &
		  SECBF(MAX_GRIDS,MAX_YEARS,12) , TRUNOFF(MAX_GRIDS,MAX_YEARS,12), &
         INTF(MAX_GRIDS,MAX_YEARS,12), RUN_HRU(MAX_GRIDS,MAX_YEARS,12),BASE_HRU(MAX_GRIDS,MAX_YEARS,12)  

! Monthly RUNOFF

       Real RUNOFF_MON, BASEFLOW_MON
       COMMON/Month_RUN/ RUNOFF_MON(MAX_GRIDS,12),BASEFLOW_MON(MAX_GRIDS,12)
      
! CLIMATE      
      REAL  RAIN,TEMP,AAPPT
      COMMON/CLIMATE/ RAIN(MAX_GRIDS,MAX_YEARS,12), TEMP(MAX_GRIDS,MAX_YEARS,12), AAPPT(MAX_GRIDS)
      
! LAI        
      REAL LAI,LAI_lc,AET_lc
      COMMON/LAI/LAI(MAX_GRIDS,MAX_YEARS,12),LAI_lc(MAX_GRIDS,MAX_YEARS,12,MAX_HUCS),AET_lc(MAX_YEARS,12,MAX_HUCS)

! SNOWPACK	
      REAL SP
	  INTEGER NSPM
      COMMON/SNOWPACK/SP(MAX_GRIDS,MAX_YEARS,12), NSPM(MAX_GRIDS,MAX_YEARS)

! SUMMARY1 
      REAL ANURAIN,ANURUN,ANUPET,ANUAET,ANUPAET,RAINALL, AETALL, PETALL, RUNALL, RUNRATIO,ETRATIO_GRD,TRATIO,RALL
	  INTEGER NUM_Year
      COMMON/SUMMARY/ANURAIN(MAX_GRIDS,MAX_YEARS),ANURUN(MAX_GRIDS,MAX_YEARS),ANUPET(MAX_GRIDS,MAX_YEARS),&
	  ANUAET(MAX_GRIDS,MAX_YEARS),ANUPAET(MAX_GRIDS,MAX_YEARS),&
	  RAINALL(MAX_GRIDS), AETALL(MAX_GRIDS), PETALL(MAX_GRIDS), RUNALL(MAX_GRIDS), RUNRATIO(MAX_GRIDS),&
	  ETRATIO_GRD(MAX_GRIDS),TRATIO(MAX_GRIDS),RALL(MAX_GRIDS),NUM_Year(MAX_GRIDS)

! SOIL parameters input
      REAL LZTWM, LZFPM, LZFSM,LZSK,LZPK, UZTWM, UZFWM, UZK, ZPERC,&
        REXP, PFREE        
      COMMON/SOIL/LZTWM(MAX_GRIDS), LZFPM(MAX_GRIDS), LZFSM(MAX_GRIDS), LZSK(MAX_GRIDS),LZPK(MAX_GRIDS), UZTWM(MAX_GRIDS), &
        &UZFWM(MAX_GRIDS),UZK(MAX_GRIDS), ZPERC(MAX_GRIDS),REXP(MAX_GRIDS), PFREE(MAX_GRIDS)

! Soil Mositure (AV-average,EM-end of month)
       REAL AVSMC,AVUZTWC,AVUZFWC,AVLZTWC,AVLZFPC,AVLZFSC,EMSMC,EMUZTWC,EMUZFWC,EMLZTWC,EMLZFPC,EMLZFSC
	   COMMON/SMC/AVSMC(MAX_GRIDS,MAX_YEARS,12),AVUZTWC(MAX_GRIDS,MAX_YEARS,12), AVUZFWC(MAX_GRIDS,MAX_YEARS,12), &
	   AVLZTWC(MAX_GRIDS,MAX_YEARS,12), AVLZFPC(MAX_GRIDS,MAX_YEARS,12),AVLZFSC(MAX_GRIDS,MAX_YEARS,12), &
	   EMSMC(MAX_GRIDS,MAX_YEARS,12),EMUZTWC(MAX_GRIDS,MAX_YEARS,12),EMUZFWC(MAX_GRIDS,MAX_YEARS,12),&
	   EMLZTWC(MAX_GRIDS,MAX_YEARS,12), EMLZFPC(MAX_GRIDS,MAX_YEARS,12),EMLZFSC(MAX_GRIDS,MAX_YEARS,12)
	   
! FLOW 
      REAL STRFLOW,STRET,STRGEP     
      COMMON/FLOW/STRFLOW(MAX_GRIDS,MAX_YEARS,12),STRET(MAX_GRIDS,MAX_YEARS,12)&
     ,STRGEP(MAX_GRIDS,MAX_YEARS,12)

! CARBON
        REAL GEPM,RECOM,NEEM,GEPA,NEEA,AHUCGEP, AHUCNEE,AHUCRE
		INTEGER NUM_YEAR_C
      COMMON/CARBON/ GEPM(MAX_GRIDS,MAX_YEARS,12),RECOM(MAX_GRIDS,MAX_YEARS,12), &
      NEEM(MAX_GRIDS,MAX_YEARS,12),GEPA(MAX_GRIDS,MAX_YEARS),NEEA(MAX_GRIDS,MAX_YEARS)&
	  ,AHUCGEP(MAX_GRIDS), AHUCNEE(MAX_GRIDS),AHUCRE(MAX_GRIDS),NUM_YEAR_C(MAX_GRIDS)
      
! BYLAND   
!      REAL,POINTER:: RUNLAND(:,:,:,:),ETLAND(:,:,:,:),GEPLAND(:,:,:,:)
!	   COMMON/BYLAND/RUNLAND,ETLAND,GEPLAND
!      REAL RUNLAND,ETLAND,GEPLAND    
!      COMMON/BYLAND/ RUNLAND(MAX_GRIDS,MAX_YEARS,12,31), &
!        ETLAND(MAX_GRIDS,MAX_YEARS,12,31), GEPLAND(MAX_GRIDS,MAX_YEARS,12,31)

! HUCPETAET
      REAL HUCAET, HUCPET,HUCPAET
      COMMON/HUCPETAET/HUCAET(MAX_GRIDS,MAX_YEARS), HUCPET(MAX_GRIDS,MAX_YEARS),&
      HUCPAET(MAX_GRIDS,MAX_YEARS)

! LANDCHANGE     
      REAL FPERD, FPERDLAI  
      COMMON/LANDCHANGE/FPERD,FPERDLAI
        
! R	  
	  REAL RFACTOR,ETRATIO,ARUNRT,AETRT 
      COMMON/R/ RFACTOR(MAX_GRIDS,MAX_YEARS),ETRATIO(MAX_GRIDS,MAX_YEARS),&
	  ARUNRT(MAX_GRIDS,MAX_YEARS), AETRT(MAX_GRIDS,MAX_YEARS)
	  
	 	  
      end


!**************---Program Starting--------*************************